name: SkipUI CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
  #schedule:
    # run at 9AM & 9PM UTC
    #- cron:  '0 9,21 * * *'

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  ci:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - name: Test macOS
        run: |
          swift test
      - name: Build (Debug)
        run: |
            xcodebuild build \
              -configuration Build \
              -skipPackagePluginValidation \
              -scheme "SkipUIX" \
              -sdk "iphonesimulator" \
              -destination "platform=iOS Simulator,name=iPhone 14"
      - name: Test (SkipUI / Debug)
        run: |
            xcodebuild test \
              -configuration Debug \
              -skipPackagePluginValidation \
              -scheme "SkipUIX" \
              -sdk "iphonesimulator" \
              -destination "platform=iOS Simulator,name=iPhone 14"
      - name: Test (SwiftUI / Release)
        run: |
            xcodebuild test \
              -configuration Release \
              -skipPackagePluginValidation \
              -scheme "SkipUIX" \
              -sdk "iphonesimulator" \
              -destination "platform=iOS Simulator,name=iPhone 14"

